### ISSUE TITLE
Интеграция счётчика газа Соник 4G-ТК

### ISSUE THREAD

**Issue by YuriyCC** [SzenProgs/elehant_water#1]
Завтра отсканирую эфир и добавлю сюда mac

**Comment by YuriyCC** [comment]
![IMG_20230228_202857.jpg](https://user-images.githubusercontent.com/99243957/221868160-3b1bbb92-846f-46c4-b9af-1718ca6ebb8e.jpg)

Доброго дня.Ну вот такое в эфире. Другого нет

**Comment by SzenProgs** [comment]
Принял. Посмотрю

**Comment by SzenProgs** [comment]
Обновляйтесь. Актуальная версия - 0.5.8

**Comment by YuriyCC** [comment]
Вечер добрый. Завтра буду дома, проверю, обязательно сообщу результат.

**Comment by YuriyCC** [comment]
Ничего не получается. Датчик есть но показания отсутствуют. Может я в конфиг не то прописываю? Или как иначе выяснить в чем проблема?

**Comment by SzenProgs** [comment]
Конфиг сенсора в студию.
И еще, счетчик иногда засыпает и перестаёт передавать данные в эфир. Просыпается, когда через него начинает идти газ (или вода).

**Comment by YuriyCC** [comment]
#Датчики газа, воды и т.д    
  
  - platform: elehant_water
    scan_duration: 10
    scan_interval: 6
    measurement_water: m3
    measurement_gas: m3
    devices:
      - id: 4109
        type: gas
        name: "Счетчик газа5

**Comment by YuriyCC** [comment]
> Конфиг сенсора в студию.
> И еще, счетчик иногда засыпает и перестаёт передавать данные в эфир. Просыпается, когда через него начинает идти газ (или вода).

В сканере ble он появляется

**Comment by SzenProgs** [comment]
Внес правки. Обновитесь.
В конфиге не вижу закрывающих кавычек в параметре name, но думаю, это ваша опечатка. Иначе сервер не дал бы вам перезагрузиться, чтобы новые параметры вступили в силу.

**Comment by YuriyCC** [comment]
Да опечатка тут

**Comment by YuriyCC** [comment]
Добрый день. Сегодня добрался до счётчика на коттедже. Наконец то он его увидел. Но появилась другая проблема на моем счётчике (показания на дисплее прибора) 7049 а на счётчике в ha  339 без мелких знаков после запятой

**Comment by SzenProgs** [comment]
Возможно проблемы с размером выбираемого стека значений из payload. Подобная проблема была с размером стека, где брался номер счетчика. 4-х цифровые работали, а счётчики с номером из пяти символов уже не находились. 
В течение получаса попробую расширить стек у себя и отпишусь.

**Comment by SzenProgs** [comment]
Забирайте новую версию.

**Comment by YuriyCC** [comment]
Благодарю за скорость. Постараюсь завтра дать обратную связь

**Comment by YuriyCC** [comment]
Вечер добрый. Наконец то заработало. Теперь все показывает корректно. Полноценные показатели. Только есть один вопрос, почему id объекта voda kholodnaia kuhnia 2. Хотя настроен как газовый счётчик.

**Comment by YuriyCC** [comment]
Возможно старые названия в системе остались. Попробую удалить все и по новой завести в систему интеграцию

**Comment by SzenProgs** [comment]
Удалите сенсор, перезагрузите сервер. ID кешируются.

**Comment by YuriyCC** [comment]
Да все получилось после удаления появился новый нормальный датчик

**Comment by SzenProgs** [comment]
Добавлено с версии 0.6.1. Проблему закрываю.
